services:
  xblapp.ui:
    image: xbl-service-image:latest
    build:
      context: .
      dockerfile: XblApp.UI\Dockerfile
    ports:
    - "5000:80"
    container_name: xbox-web-container
    environment:
    - ASPNETCORE_ENVIRONMENT=Docker
    - ASPNETCORE_URLS=http://+:80
    networks:
    - productnetwork
    #restart: on-failure 
    depends_on:
    - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
        SA_PASSWORD: "Password12345!"
        ACCEPT_EULA: "Y"
    ports:
    - "1433:1433"
    volumes:
    - sqlvolume:/var/opt/mssql
    networks:
    - productnetwork

networks:
    productnetwork:
  
volumes:
  sqlvolume:  
