// <auto-generated />
using System;
using ConsoleApp.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConsoleApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConsoleApp.Authentication.OAuth2TokenResponse", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)")
                        .HasAnnotation("Relational:JsonPropertyName", "user_id");

                    b.Property<string>("AccessToken")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "access_token");

                    b.Property<string>("AuthenticationToken")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "authentication_token");

                    b.Property<DateTime?>("Expires")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "expires");

                    b.Property<int>("ExpiresIn")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "expires_in");

                    b.Property<DateTime?>("Issued")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "issued");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "refresh_token");

                    b.Property<string>("Scope")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "scope");

                    b.Property<string>("TokenType")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "token_type");

                    b.HasKey("UserId");

                    b.ToTable("OAuth2TokenResponses");
                });

            modelBuilder.Entity("ConsoleApp.Authentication.XSTSResponse", b =>
                {
                    b.Property<string>("Xuid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("IssueInstant")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "IssueInstant");

                    b.Property<DateTime>("NotAfter")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "NotAfter");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "Token");

                    b.HasKey("Xuid");

                    b.ToTable("XSTSResponses");
                });
#pragma warning restore 612, 618
        }
    }
}
